### ISSUE TITLE
how would i select out of two resolutions that start with same width

### ISSUE THREAD

**Issue by sarabsandhu** [th507/screen-resolution-switcher#1]
For example, lets say my list of resolutions for display 0 is as below 
Supported Modes for Display 0:
       1440 * 900 @ 60Hz
       1152 * 720 @ 60Hz
       1024 * 768 @ 60Hz
       1024 * 640 @ 60Hz
       1280 * 800 @ 60Hz
       800 * 600 @ 60Hz
       800 * 500 @ 60Hz
       640 * 480 @ 60Hz
       720 * 480 @ 60Hz

if I am using command "retina -s 0 1024", it is always selecting first resolution to switch. How can i select 1024*640 resolution instead of 1024*768.

**Comment by th507** [comment]
Supported in  faee7140a3dced1ce9a02776b7d4d31172b46417.
You could use `-s [width], [height]` to select mode with different height.
Check out [README](https://github.com/th507/screen-resolution-switcher/blob/master/README.md) for extensive usage examples.

**Comment by th507** [comment]
Supported in  fc006adb4c86676f187eab7f9a007c2762f91b64.
You could use `-s [width], [height]` to select mode with different height.
Check out [README](https://github.com/th507/screen-resolution-switcher/blob/master/README.md) for extensive usage examples.
