### ISSUE TITLE
Lower refresh rate is prioritized

### ISSUE THREAD

**Issue by miyagawa** [th507/screen-resolution-switcher#4]
First of all, thank you for this tool. I have a weird issue with M1 Mac mini and LG 4K display where the display resolution gets changed after sleep/wake, and while that is pretty annoying, I'm able to fix it pretty easily using the scres tool.

Now, the set command (-s) seems to find the first display resolution that matches with the input, and I can't find a way to provide the desired refresh rate. My display offers the same resolution in both 30Hz and 60Hz, and scres picks the 30Hz since it comes first, which is not what I want.

```
> scres -m | grep 3008
     3008 x 1692 @ 2x @ 30Hz
  ⮕  3008 x 1692 @ 2x @ 60Hz
     3008 x 1692 @ 1x @ 30Hz
     3008 x 1692 @ 1x @ 60Hz
> scres -s 3008
> scres -m | grep 3008
  ⮕  3008 x 1692 @ 2x @ 30Hz
     3008 x 1692 @ 2x @ 60Hz
     3008 x 1692 @ 1x @ 30Hz
     3008 x 1692 @ 1x @ 60Hz
```

I'm currently working around by hard coding to always prefer 60Hz in the code, but would be nice if the `-s` command accepts the refresh rate as well, or sort the configurations by the refresh rate after retina scaling so that higher refresh rate is preferred.

**Comment by th507** [comment]
Fixed in [9e883d1d1](https://github.com/th507/screen-resolution-switcher/commit/9e883d1d195a6a473b0c05e3ecb0e9834124ae88)
